name: Build and publish containers and charts

on:
  push:
    branches:
      - main

env:
  NIARTIFACTS_USER: ${{ secrets.NIARTIFACTS_USER }}
  NIARTIFACTS_REGISTRY: niartifacts.jfrog.io
  NIARTIFACTS_PASSWORD: ${{ secrets.NIARTIFACTS_PASSWORD }}
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
  DOCKERHUB_REGISTRY: docker.io
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  PRIVATE_KEY: ${{ secrets.NI_PRIVATE_KEY }}
  PUBLIC_KEY: ${{ secrets.NI_PUB_KEY }}
  KEY_ID: ${{ secrets.NI_KEY_ID }}
  IMAGE_TAG: niartifacts.jfrog.io/rdsdck/test-image:${{ github.run_id }}

jobs:
  build-publish-containers:
    env:
      GNUPGHOME: ${{ runner.temp }}/.gnupg
      SIGSTORE: ${{ runner.temp }}/sigstore
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log into Artifactory
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.NIARTIFACTS_USER }}
          password: ${{ env.NIARTIFACTS_PASSWORD}}
          registry: ${{ env.NIARTIFACTS_REGISTRY }}
      - name: Log into DockerHub
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.NIARTIFACTS_USER }}
          password: ${{ env.NIARTIFACTS_PASSWORD}}
          registry: ${{ env.NIARTIFACTS_REGISTRY }}
      - name: Build container
        run: podman build -t $IMAGE_TAG .
      - name: Push container
        run: podman push $IMAGE_TAG
      - name: Create gnupghome
        run: mkdir $GNUPGHOME
      - name: Create sigstore directory
        run: mkdir $SIGSTORE
      - name: Import Private Key
        run: echo $PRIVATE_KEY | gpg --import
      - name: Import Public Key
        run: echo $PUBLIC_KEY | gpg --import
      - name: Sign image
        run: podman image sign --sign-by $KEY_ID -d $SIGSTORE $IMAGE_TAG
      - name: Show signatures
        run: ls $SIGSTORE/rdsdck
  