name: Build and publish containers and charts

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NIARTIFACTS_USER: ${{ secrets.NIARTIFACTS_USER }}
  NIARTIFACTS_PASSWORD: ${{ secrets.NIARTIFACTS_PASSWORD }}
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
  DOCKERHUB_REGISTRY: docker.io
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  IMAGE_TAG: niartifacts.jfrog.io/rdsdck/test-image:${{ github.run_id }}

jobs:
  build-publish-containers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log into Artifactory
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.NIARTIFACTS_USER }}
          password: ${{ env.NIARTIFACTS_PASSWORD}}
          registry: ${{ env.NIARTIFACTS_REGISTRY }}
      - name: Log into DockerHub
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.NIARTIFACTS_USER }}
          password: ${{ env.NIARTIFACTS_PASSWORD}}
          registry: ${{ env.NIARTIFACTS_REGISTRY }}
      - name: Build container
        run: podman build -t $IMAGE_TAG .
      - name: Push container
        run: podman push $IMAGE_TAG
        
  sign-container:
    uses: ni/workflows/.github/workflows/sign-container.yml@users/nstoddar/add-sign-container-workflow
    with:
      gpg_key_id: ${{ secrets.NI_KEY_ID }}
      image_tag: ${{ env.IMAGE_TAG }}
      registry_username: ${{ secrets.NIARTIFACTS_USER }}
      signature_store_bucket: s3://signing-web-demo-bucket-1neyh347t53dt
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GPG_PRIVATE_KEY: ${{ secrets.NI_PRIVATE_KEY }}
      GPG_PUBLIC_KEY: ${{ secrets.NI_PUB_KEY }}
      REGISTRY_PASSWORD: ${{ secrets.NIARTIFACTS_PASSWORD }}
