name: Build and publish containers and charts

on:
  push:
    branches:
      - main

env:
  NIARTIFACTS_USER: ${{ secrets.NIARTIFACTS_USER }}
  NIARTIFACTS_REGISTRY: niartifacts.jfrog.io
  NIARTIFACTS_PASSWORD: ${{ secrets.NIARTIFACTS_PASSWORD }}
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
  DOCKERHUB_REGISTRY: docker.io
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}


  KEY_ID: ${{ secrets.NI_KEY_ID }}
  IMAGE_TAG: niartifacts.jfrog.io/rdsdck/test-image:${{ github.run_id }}

jobs:
  build-publish-containers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create gnupghome
        run: mkdir ${{ runner.temp }}/gpg
      - name: Create sigstore directory
        run: mkdir ${{ runner.temp }}/sigstore
      - name: Create public key file
        env:
          PUBLIC_KEY: ${{ secrets.NI_PUB_KEY }}
        run: echo "$PUBLIC_KEY" | base64 --decode > $RUNNER_TEMP/pubring.asc
      - name: Create private key file
        env:
          PRIVATE_KEY: ${{ secrets.NI_PRIVATE_KEY }}
        run: echo "$PRIVATE_KEY" | base64 --decode > $RUNNER_TEMP/secring.asc
      - name: Print public key
        run: cat $RUNNER_TEMP/pubring.asc
      - name: Import Public Key
        run: GNUPGHOME=${{ runner.temp }}/gnupg bash -c 'cat $RUNNER_TEMP/pubring.asc | gpg --import'
      - name: Import Private Key
        run: GNUPGHOME=${{ runner.temp }}/gnupg bash -c 'cat $RUNNER_TEMP/secring.asc | gpg --import'
      - name: Log into Artifactory
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.NIARTIFACTS_USER }}
          password: ${{ env.NIARTIFACTS_PASSWORD}}
          registry: ${{ env.NIARTIFACTS_REGISTRY }}
      - name: Log into DockerHub
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.NIARTIFACTS_USER }}
          password: ${{ env.NIARTIFACTS_PASSWORD}}
          registry: ${{ env.NIARTIFACTS_REGISTRY }}
      - name: Build container
        run: podman build -t $IMAGE_TAG .
      - name: Push container
        run: podman push $IMAGE_TAG
      - name: Sign image
        run: GNUPGHOME=${{ runner.temp }}/gnupg podman image sign --sign-by $KEY_ID -d ${{ runner.temp }}/sigstore $IMAGE_TAG
      - name: Show signatures
        run: ls ${{ runner.temp }}/rdsdck
  