name: Build and publish containers and charts

on:
  push:
    branches:
      - main
  workflow_dispatch:  

jobs:
  build-publish-containers:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: niartifacts.jfrog.io/rdsdck/test-image:${{ github.run_id }}
    steps:
      - uses: actions/checkout@v3
      - name: Log into Artifactory
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ secrets.NIARTIFACTS_USER }}
          password: ${{ secrets.NIARTIFACTS_PASSWORD }}
          registry: niartifacts.jfrog.io
      - name: Log into DockerHub
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          registry: docker.io
      - name: Build container
        run: podman build -t $IMAGE_TAG .
      - name: Push container
        run: podman push $IMAGE_TAG
        
  sign-container:
    uses: ni/workflows/.github/workflows/sign-container.yml@users/nstoddar/add-sign-container-workflow
    needs: build-publish-containers
    with:
      image_tag: niartifacts.jfrog.io/rdsdck/test-image:${{ github.run_id }}
      registry_username: neil.stoddard@ni.com
      signature_store_bucket: s3://signing-web-demo-bucket-1neyh347t53dt
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GPG_PRIVATE_KEY: ${{ secrets.NI_PRIVATE_KEY }}
      REGISTRY_PASSWORD: ${{ secrets.NIARTIFACTS_PASSWORD }}
  
  build-publish-chart:
    runs-on: ubuntu-latest
    env:
      CHART_VERSION: '0.1.${{ github.run_id }}'
    steps:
      - uses: actions/checkout@v3
      - name: Build chart package
        run: helm package test-chart --destination ${{ runner.temp }} --version ${{ env.CHART_VERSION }}
      - name: Publish chart
        run: curl -H "X-JFrog-Art-Api:${{ secrets.NIARTIFACTS_PASSWORD }}" -T ${{ runner.temp }}/test-chart-${{ env.CHART_VERSION }}.tgz "https://niartifacts.jfrog.io/artifactory/rds-hlm/ni/test-chart/test-chart-${{ env.CHART_VERSION }}.tgz"

  sign-chart:
    uses: ni/workflows/.github/workflows/sign-chart.yml@users/nstoddar/add-sign-container-workflow
    needs: build-publish-chart
    with:
      chart: test-chart
      repository_name: rds-hlm
      repository_path: /ni/test-chart/
      repository_user: neil.stoddard@ni.com
      version: '0.1.${{ github.run_id }}'
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.NI_PRIVATE_KEY }}
      REPOSITORY_PASSWORD: ${{ secrets.NIARTIFACTS_PASSWORD }}      
